const assert = require("node:assert/strict");
const R = require("./round-state.js");
const E = require("./score-engine.js");

const base = "http://127.0.0.1:8080";
let scoreTokens = {};
let adminPin = "2468";
async function action(type, payload = {}, options = {}) {
  const headers = { "Content-Type": "application/json", "X-Scoring-Group": options.group || "A" };
  if (R.isAdminAction(type) || options.admin) {
    headers["X-Admin-Pin"] = options.pin || adminPin;
    headers["X-Admin-Override"] = "1";
  } else if (R.isScoringAction(type) && !options.noToken) {
    headers["X-Scoring-Token"] = options.token ?? scoreTokens[options.group || "A"] ?? "";
  }
  const response = await fetch(`${base}/api/action`, { method: "POST", headers, body: JSON.stringify({ type, payload }) });
  assert.equal(response.status, options.status || 200);
  return response;
}

async function playerRequest(path = "", options = {}) {
  const headers = { ...(options.headers || {}), "X-Admin-Pin": options.pin || adminPin };
  if (options.body) headers["Content-Type"] = "application/json";
  const response = await fetch(`${base}/api/players${path}`, { method: options.method || "GET", headers, body: options.body ? JSON.stringify(options.body) : undefined });
  assert.equal(response.status, options.status || 200);
  return response.json();
}

async function adminRequest(path = "", options = {}) {
  const headers = { ...(options.headers || {}), "X-Admin-Pin": options.pin || adminPin };
  if (options.body) headers["Content-Type"] = "application/json";
  const response = await fetch(`${base}/api/admins${path}`, { method: options.method || "GET", headers, body: options.body ? JSON.stringify(options.body) : undefined });
  assert.equal(response.status, options.status || 200);
  return response.json();
}

(async () => {
  const config = await (await fetch(`${base}/api/config`)).json();
  assert.equal(config.appVersion, "9.10.0");
  assert.equal(config.adminSetupRequired, true);
  const scorecardExportAsset = await fetch(`${base}/scorecard-export.js`);
  assert.equal(scorecardExportAsset.status, 200);
  const sortingAsset = await fetch(`${base}/leaderboard-sort.js`);
  assert.equal(sortingAsset.status, 200);
  const wrongPin = await fetch(`${base}/api/admin/check`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pin: "wrong" }) });
  assert.equal(wrongPin.status, 401);
  const rightPin = await fetch(`${base}/api/admin/check`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pin: "2468" }) });
  assert.equal(rightPin.status, 200);
  assert.equal((await rightPin.json()).admin.bootstrap, true);
  const firstAdmin = await adminRequest("", { method: "POST", status: 201, pin: "2468", body: { name: "Alice Admin", pin: "1357" } });
  assert.equal(firstAdmin.admin.name, "Alice Admin");
  adminPin = "1357";
  const disabledSetupPin = await fetch(`${base}/api/admin/check`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pin: "2468" }) });
  assert.equal(disabledSetupPin.status, 401);
  const aliceLogin = await fetch(`${base}/api/admin/check`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pin: adminPin }) });
  assert.equal(aliceLogin.status, 200);
  assert.equal((await aliceLogin.json()).admin.name, "Alice Admin");
  const adminList = await adminRequest();
  assert.equal(adminList.admins.length, 1);
  assert.equal(Object.hasOwn(adminList.admins[0], "pin_hash"), false);
  await adminRequest("", { method: "POST", status: 403, body: { name: "Direct Admin", pin: "8642" } });
  const inviteResponse = await fetch(`${base}/api/admin-invitations`, { method: "POST", headers: { "X-Admin-Pin": adminPin, "Content-Type": "application/json" }, body: JSON.stringify({ hours: 24 }) });
  assert.equal(inviteResponse.status, 201);
  const invitation = (await inviteResponse.json()).invitation;
  const acceptInvite = await fetch(`${base}/api/admin-invitations/accept`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token: invitation.token, name: "Bob Admin", pin: "8642" }) });
  assert.equal(acceptInvite.status, 201);
  const reuseInvite = await fetch(`${base}/api/admin-invitations/accept`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token: invitation.token, name: "Reuse", pin: "1111" }) });
  assert.equal(reuseInvite.status, 410);
  const bobLogin = await fetch(`${base}/api/admin/check`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pin: "8642" }) });
  assert.equal(bobLogin.status, 200);
  const bob = (await bobLogin.json()).admin;
  await action("SET_META", { roundName: "Named admin audit test" }, { pin: "8642" });
  const namedAuditState = await (await fetch(`${base}/api/state`)).json();
  assert.equal(namedAuditState.auditLog.at(-1).actor, "Bob Admin");
  await adminRequest(`/${bob.id}`, { method: "PUT", status: 403, body: { pin: "9999" } });
  await adminRequest(`/${bob.id}`, { method: "DELETE" });
  const removedBobLogin = await fetch(`${base}/api/admin/check`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ pin: "8642" }) });
  assert.equal(removedBobLogin.status, 401);
  await adminRequest(`/${firstAdmin.admin.id}`, { method: "DELETE", status: 400 });
  const unauthorizedTokens = await fetch(`${base}/api/share-tokens`);
  assert.equal(unauthorizedTokens.status, 401);
  const tokenResponse = await fetch(`${base}/api/share-tokens`, { headers: { "X-Admin-Pin": adminPin } });
  assert.equal(tokenResponse.status, 200);
  scoreTokens = (await tokenResponse.json()).tokens;
  assert.equal(Object.keys(scoreTokens).length, 6);
  const priorRoundState = await (await fetch(`${base}/api/state`)).json();
  const priorTokens = { ...scoreTokens };
  const unauthorizedRounds = await fetch(`${base}/api/rounds`);
  assert.equal(unauthorizedRounds.status, 401);
  const unauthorizedPlayers = await fetch(`${base}/api/players`);
  assert.equal(unauthorizedPlayers.status, 401);
  const unauthorizedBackup = await fetch(`${base}/api/system-backup`);
  assert.equal(unauthorizedBackup.status, 401);
  const unauthorizedReadiness = await fetch(`${base}/api/readiness`);
  assert.equal(unauthorizedReadiness.status, 401);
  const createdSaved = await playerRequest("", { method: "POST", status: 201, body: { name: "Saved Golfer", ghin: 15.2, teeKey: "championship" } });
  assert.equal(createdSaved.player.ghin, 15.2);
  const listedSaved = await playerRequest();
  assert.equal(listedSaved.players.some((player) => player.id === createdSaved.player.id), true);
  const updatedSaved = await playerRequest(`/${createdSaved.player.id}`, { method: "PUT", body: { ghin: 13.7 } });
  assert.equal(updatedSaved.player.ghin, 13.7);
  const completeBackupResponse = await fetch(`${base}/api/system-backup`, { headers: { "X-Admin-Pin": adminPin } });
  assert.equal(completeBackupResponse.status, 200);
  const completeBackup = await completeBackupResponse.json();
  assert.equal(completeBackup.format, "berry-creek-complete-backup");
  assert.equal(completeBackup.savedPlayers.some((player) => player.id === createdSaved.player.id), true);
  const snapshotResponse = await fetch(`${base}/api/system-backup/snapshot`, { method: "POST", headers: { "X-Admin-Pin": adminPin, "Content-Type": "application/json" }, body: "{}" });
  assert.equal(snapshotResponse.status, 201);
  const readiness = await (await fetch(`${base}/api/readiness`, { headers: { "X-Admin-Pin": adminPin } })).json();
  assert.equal(Array.isArray(readiness.checks), true);
  assert.equal(readiness.checks.some((check) => check.key === "backup" && check.ok), true);
  assert.equal(readiness.checks.some((check) => check.key === "pin" && check.ok), true);
  const restoredBackup = await fetch(`${base}/api/system-backup/restore`, { method: "POST", headers: { "X-Admin-Pin": adminPin, "Content-Type": "application/json" }, body: JSON.stringify({ backup: completeBackup }) });
  assert.equal(restoredBackup.status, 200);
  assert.equal((await restoredBackup.json()).savedPlayerCount, 1);
  await playerRequest(`/${createdSaved.player.id}`, { method: "DELETE" });
  const emptySaved = await playerRequest();
  assert.equal(emptySaved.players.some((player) => player.id === createdSaved.player.id), false);
  await action("CLEAR_ROUND");
  const clearedState = await (await fetch(`${base}/api/state`)).json();
  assert.notEqual(clearedState.roundId, priorRoundState.roundId);
  const currentTokenResponse = await fetch(`${base}/api/share-tokens`, { headers: { "X-Admin-Pin": adminPin } });
  scoreTokens = (await currentTokenResponse.json()).tokens;
  assert.notEqual(scoreTokens.A, priorTokens.A);
  const streamResponse = await fetch(`${base}/api/events`);
  assert.equal(streamResponse.status, 200);
  const reader = streamResponse.body.getReader();
  await reader.read();

  await Promise.all([
    action("ADD_PLAYER", { player: { id: "live-a", directoryId: "saved-live-a", name: "Live A", group: "A", teeKey: "championship", ghin: 10 } }),
    action("ADD_PLAYER", { player: { id: "live-b", name: "Live B", group: "B", teeKey: "member", ghin: 18 } })
  ]);
  await action("ADD_PLAYER", { player: { id: "live-a-duplicate", directoryId: "saved-live-a", name: "Live A duplicate", group: "C" } }, { status: 409 });
  const uniqueActiveState = await (await fetch(`${base}/api/state`)).json();
  assert.equal(uniqueActiveState.players.length, 2);
  assert.equal(uniqueActiveState.players.some((player) => player.id === "live-a-duplicate"), false);
  await action("SET_SCORE", { playerId: "live-a", holeIndex: 0, score: 4 }, { group: "A", token: priorTokens.A, status: 403 });
  await Promise.all([
    action("SET_SCORE", { playerId: "live-a", holeIndex: 0, score: 4, expectedScore: "" }, { group: "A" }),
    action("SET_SCORE", { playerId: "live-b", holeIndex: 0, score: 5, expectedScore: "" }, { group: "B" })
  ]);
  const update = new TextDecoder().decode((await reader.read()).value);
  assert.match(update, /event: state/);
  const state = await (await fetch(`${base}/api/state`)).json();
  assert.equal(state.players.length, 2);
  assert.equal(state.players.find((p) => p.id === "live-a").scores[0], 4);
  assert.equal(state.players.find((p) => p.id === "live-b").scores[0], 5);
  await action("SET_SCORE", { playerId: "live-b", holeIndex: 1, score: 3 }, { group: "B" });
  await action("SET_KP", { hole: 2, playerId: "live-a" }, { group: "A" });
  await action("SET_KP", { hole: 2, playerId: "live-b" }, { group: "B" });
  let kpState = await (await fetch(`${base}/api/state`)).json();
  assert.equal(kpState.settings.kpWinners["2"], "live-b");
  assert.deepEqual(kpState.settings.kpClaims["2"], ["live-a", "live-b"]);
  assert.equal(E.ticSummary(kpState.players.find((player) => player.id === "live-a"), kpState.players, E.COURSE, kpState.settings).kps, 0);
  assert.equal(E.ticSummary(kpState.players.find((player) => player.id === "live-a"), kpState.players, E.COURSE, kpState.settings).kpMarked, 1);
  assert.equal(E.ticSummary(kpState.players.find((player) => player.id === "live-a"), kpState.players, E.COURSE, kpState.settings).kpThreePutts, 0);
  assert.equal(E.ticSummary(kpState.players.find((player) => player.id === "live-b"), kpState.players, E.COURSE, kpState.settings).kps, 1);
  await action("UNDO_LAST", { group: "B" }, { group: "B" });
  kpState = await (await fetch(`${base}/api/state`)).json();
  assert.equal(kpState.settings.kpWinners["2"], "live-a");
  assert.deepEqual(kpState.settings.kpClaims["2"], ["live-a"]);
  await action("SET_KP", { hole: 2, playerId: "live-b" }, { group: "B" });
  await action("SET_SCORE", { playerId: "live-b", holeIndex: 1, score: 4 }, { group: "B" });
  kpState = await (await fetch(`${base}/api/state`)).json();
  assert.equal(E.ticSummary(kpState.players.find((player) => player.id === "live-b"), kpState.players, E.COURSE, kpState.settings).kps, 0);
  assert.equal(E.ticSummary(kpState.players.find((player) => player.id === "live-b"), kpState.players, E.COURSE, kpState.settings).kpMarked, 0);
  assert.equal(E.ticSummary(kpState.players.find((player) => player.id === "live-b"), kpState.players, E.COURSE, kpState.settings).kpThreePutts, 1);
  assert.equal(kpState.players.reduce((sum, player) => sum + E.ticSummary(player, kpState.players, E.COURSE, kpState.settings).kps, 0), 0);
  await action("SET_SCORE", { playerId: "live-b", holeIndex: 1, score: 3 }, { group: "B" });
  await action("UNDO_LAST", { group: "A" }, { group: "A" });
  const undoneState = await (await fetch(`${base}/api/state`)).json();
  assert.equal(undoneState.players.find((p) => p.id === "live-a").scores[0], "");
  await action("SET_SCORE", { playerId: "live-a", holeIndex: 0, score: 4 }, { group: "A" });
  const conflictResponse = await action("SET_SCORE", { playerId: "live-a", holeIndex: 0, score: 5, expectedScore: "" }, { group: "A", status: 409 });
  const conflict = await conflictResponse.json();
  assert.equal(conflict.code, "SCORE_CONFLICT");
  assert.equal(conflict.conflict.currentScore, 4);
  await action("SET_SCORE", { playerId: "live-a", holeIndex: 0, score: 5, expectedScore: "", force: true }, { group: "A" });
  await action("SET_SCORE", { playerId: "live-a", holeIndex: 0, score: 4, expectedScore: 5 }, { group: "A" });
  await action("SET_SCORE", { playerId: "live-a", holeIndex: 1, score: 3 }, { group: "A", noToken: true, status: 403 });
  await action("SET_SCORE", { playerId: "live-b", holeIndex: 1, score: 3 }, { group: "A", status: 403 });
  const savedRoundResponse = await fetch(`${base}/api/rounds`, { method: "POST", headers: { "X-Admin-Pin": adminPin, "Content-Type": "application/json" }, body: "{}" });
  assert.equal(savedRoundResponse.status, 201);
  const savedRound = (await savedRoundResponse.json()).round;
  const savedRounds = await (await fetch(`${base}/api/rounds`, { headers: { "X-Admin-Pin": adminPin } })).json();
  assert.equal(savedRounds.rounds.some((round) => round.id === savedRound.id), true);
  const savedRoundDetail = await (await fetch(`${base}/api/rounds/${savedRound.id}`, { headers: { "X-Admin-Pin": adminPin } })).json();
  assert.equal(savedRoundDetail.round.state.players.length, 2);
  const historyBackup = await (await fetch(`${base}/api/system-backup`, { headers: { "X-Admin-Pin": adminPin } })).json();
  assert.equal(historyBackup.savedRounds.some((round) => round.id === savedRound.id), true);
  const deletedRound = await fetch(`${base}/api/rounds/${savedRound.id}`, { method: "DELETE", headers: { "X-Admin-Pin": adminPin } });
  assert.equal(deletedRound.status, 200);
  const restoredHistory = await fetch(`${base}/api/system-backup/restore`, { method: "POST", headers: { "X-Admin-Pin": adminPin, "Content-Type": "application/json" }, body: JSON.stringify(historyBackup) });
  assert.equal(restoredHistory.status, 200);
  const restoredRounds = await (await fetch(`${base}/api/rounds`, { headers: { "X-Admin-Pin": adminPin } })).json();
  assert.equal(restoredRounds.rounds.some((round) => round.id === savedRound.id), true);
  await fetch(`${base}/api/rounds/${savedRound.id}`, { method: "DELETE", headers: { "X-Admin-Pin": adminPin } });
  await action("SET_LOCKED", { locked: true });
  await action("SET_SCORE", { playerId: "live-a", holeIndex: 1, score: 3 }, { group: "A", status: 423 });
  await action("SET_LOCKED", { locked: false });
  await action("RESET_SCORES");
  const resetState = await (await fetch(`${base}/api/state`)).json();
  assert.equal(resetState.players.length, 2);
  assert.equal(resetState.players.every((player) => player.scores.every((score) => score === "")), true);
  assert.deepEqual(resetState.settings.kpClaims, {});
  assert.equal(resetState.auditLog.length > 0, true);
  const rosterTemplate = { ...resetState, roundId: "reused-roster-test-round", players: resetState.players.map((player) => ({ ...player, scores: Array(18).fill(4), sandies: Array(18).fill(true) })) };
  await action("START_FROM_SAVED", { state: rosterTemplate });
  const reusedState = await (await fetch(`${base}/api/state`)).json();
  assert.equal(reusedState.roundId, "reused-roster-test-round");
  assert.equal(reusedState.players.length, 2);
  assert.equal(reusedState.players.every((player) => player.scores.every((score) => score === "")), true);
  assert.equal(reusedState.players.every((player) => player.sandies.every((value) => value === false)), true);
  const reusedTokenResponse = await fetch(`${base}/api/share-tokens`, { headers: { "X-Admin-Pin": adminPin } });
  const reusedTokens = (await reusedTokenResponse.json()).tokens;
  assert.notEqual(reusedTokens.A, scoreTokens.A);
  await reader.cancel();
  await action("SET_LOCKED", { locked: true });
  await action("CLEAR_ROUND");
  const newRoundState = await (await fetch(`${base}/api/state`)).json();
  assert.equal(newRoundState.players.length, 0);
  assert.equal(newRoundState.settings.locked, false);
  console.log("Concurrent API and live-update tests passed.");
})().catch((error) => { console.error(error); process.exit(1); });
